### ISSUE TITLE
Error rendering component in tests

### ISSUE THREAD

**Issue by negomi** [FormidableLabs/radium#416]
I'm getting an error when trying to render a component for testing (using Mocha/Chai and jsdom):
```
TypeError: Cannot read property 'CSS' of undefined
      at new Prefixer (node_modules/inline-style-prefixer/lib/Prefixer.js:43:46)
      at Object.getPrefixedStyle (node_modules/radium/lib/prefixer.js:44:16)
      at prefixPlugin (node_modules/radium/lib/plugins/prefix-plugin.js:16:28)
      at node_modules/radium/lib/resolve-styles.js:184:18
      at Array.forEach (native)
      at _runPlugins (node_modules/radium/lib/resolve-styles.js:183:11)
      at resolveStyles (node_modules/radium/lib/resolve-styles.js:276:14)
      at node_modules/radium/lib/resolve-styles.js:89:14
      at mapSingleChildIntoContext (node_modules/react/lib/ReactChildren.js:105:26)
      at traverseAllChildrenImpl (node_modules/react/lib/traverseAllChildren.js:98:5)
      at traverseAllChildrenImpl (node_modules/react/lib/traverseAllChildren.js:114:23)
      at traverseAllChildren (node_modules/react/lib/traverseAllChildren.js:186:10)
      at mapIntoWithKeyPrefixInternal (node_modules/react/lib/ReactChildren.js:125:3)
      at Object.mapChildren [as map] (node_modules/react/lib/ReactChildren.js:145:3)
      at _resolveChildren (node_modules/radium/lib/resolve-styles.js:87:38)
      at Object.resolveStyles [as default] (node_modules/radium/lib/resolve-styles.js:262:21)
      at RadiumEnhancer.render (node_modules/radium/lib/enhancer.js:139:42)
      at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (node_modules/react/lib/ReactCompositeComponent.js:587:34)
      at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (node_modules/react/lib/ReactCompositeComponent.js:607:32)
      at [object Object].wrapper [as _renderValidatedComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:220:30)
      at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:37:35)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:225:34)
      at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:37:35)
      at mountComponentIntoNode (node_modules/react/lib/ReactMount.js:266:32)
      at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:282:15)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:94:20)
      at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:476:18)
      at Object.wrapper [as _renderNewRootComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:550:32)
      at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:570:23)
      at Object.wrapper [as render] (node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:76:21)
      at Context.<anonymous> (test/slide.spec.js:15:27)
```
It happens using either `TestUtils.renderIntoDocument(<Component />)` or shallow rendering, but only with Radium 0.14.4+ (reverting back to 0.14.3 works fine). Any ideas?

**Comment by ianobermiller** [comment]
0.14.4 was published by mistake, please ignore it. You may want to update to 0.15.1, which includes the new prefixer (and is the same as 0.14.4). I think the trouble here is that there is no userAgent passed to the component, and the prefixer complains during render because you aren't running in a browser environment. I didn't notice this because all our tests run in Karma under Phantom.

0.15.0+ should throw a more descriptive error which would help you fix this. Passing `radiumConfig={{userAgent: ''}}` to the component should be sufficient. This would probably be quite annoying durring tests, however. I wonder if we should just pass an empty userAgent by default, to get no prefixing.

**Comment by negomi** [comment]
Ah, that makes sense.

It doesn't seem to work with an empty string, but it does if I fake a User-Agent, e.g. `radiumConfig={{userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36'}}`. Seems to be what's suggested here as well: https://github.com/rofrischmann/inline-style-prefixer#custom-useragent

If there is a way for Radium to handle this internally for server-side test environments, that would be awesome, as it seems error-prone to have to manually specify this in every test render.

**Comment by ianobermiller** [comment]
Yeah this is definitely annoying, I believe the latest version of `inline-style-prefixer` has fixed this issue. I'll be updating Radium to use it soon.

**Comment by ianobermiller** [comment]
Fixed in a0c5791408d8050a245d0cc7620fe9cc71448f1c.

**Comment by ianobermiller** [comment]
Excellent, glad to know the fix worked. Sorry for the busted release!

**Comment by ianobermiller** [comment]
Yes, I am looking into some options for getting rid of the warning on both sides without manually passing the `userAgent`.
