### ISSUE TITLE
Radium 0.18.2 introduces babel-register error

### ISSUE THREAD

**Issue by adailey14** [FormidableLabs/radium#884]
I can't pretend to understand why, but my latest npm install updated Radium to 0.18.2, which led to this error:

```
TypeError: Super expression must either be null or a function, not undefined
    at _inherits (/var/app/current/node_modules/radium/lib/components/style.js:25:113)
    at /var/app/current/node_modules/radium/lib/components/style.js:28:3
    at Object.<anonymous> (/var/app/current/node_modules/radium/lib/components/style.js:92:2)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/var/app/current/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

Maybe someone smarter than me can make sense of that.

**Comment by ryan-roemer** [comment]
Which version of React are you using?

I don't have a deep understanding of recent changes and such, but that translates to:

```js
// lib
var Style = (_temp = _class = function (_PureComponent) {
  _inherits(Style, _PureComponent);
```

```js
// src
import React, {PropTypes, PureComponent} from 'react';

class Style extends PureComponent {
```

And it looks like maybe `React.PureComponent` was added in `15.3`? (https://60devs.com/pure-component-in-react.html)

**Comment by adailey14** [comment]
Ah, thank you. Indeed, I am using React Version 15.2.1. I guess I've grown used to ignoring some of those peer compatibility warnings from npm. I will close this issue.
